// Code generated by scripts/generate_gnark_model.py; DO NOT EDIT.
package circuit

var sepsisInitialMarking = [PlaceCount]int{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1}
var sepsisFinalMarking = [PlaceCount]int{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0}
var sepsisTransitionLabels = [TransitionCount]int{14, 5, 11, 13, 10, 6, 9, 2, 15, 16, 8, 3, 7, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
var sepsisTransitionModelCosts = [TransitionCount]int{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

// Values are zero-based transition offsets. The witness uses one-based IDs.
var sepsisInputTransitionsByPlace = [][]int{
	{11},
	{16, 32},
	{6},
	{17, 32},
	{32},
	{2, 25},
	{10, 18},
	{30},
	{19, 34},
	{30},
	{14, 22},
	{8, 28},
	{5},
	{20, 31},
	{1},
	{31},
	{12, 21},
	{13},
	{31},
	{7},
	{23, 24},
	{0, 3, 26},
	{9, 27},
	{4},
	{29, 32},
	{},
	{15, 33},
}
var sepsisOutputTransitionsByPlace = [][]int{
	{16, 33},
	{11},
	{17, 33},
	{6},
	{2, 25},
	{30},
	{33},
	{10, 18},
	{33},
	{22, 24},
	{19, 31},
	{9, 15, 27},
	{20, 34},
	{5},
	{34},
	{12, 21},
	{1},
	{34},
	{13},
	{14, 23},
	{7},
	{32},
	{0, 3, 26},
	{29, 33},
	{4},
	{8, 28},
	{},
}
