#!/usr/bin/env python3
"""Generate fixed sparse gnark model constants from circuit_model.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def go_nested(values: list[list[int]]) -> str:
    rows = ",\n".join("\t{" + ", ".join(map(str, row)) + "}" for row in values)
    return "[][]int{\n" + rows + ",\n}"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("model", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    model = json.loads(args.model.read_text())
    places = model["place_order"]
    transitions = sorted(model["transitions"], key=lambda item: item["index"])
    if len(places) != 27 or len(transitions) != 35:
        raise ValueError("expected the checked Sepsis model with 27 places and 35 transitions")

    labels = [transition["label_id"] for transition in transitions]
    model_costs = [0 if transition["silent"] else 1 for transition in transitions]
    inputs_by_place: list[list[int]] = [[] for _ in places]
    outputs_by_place: list[list[int]] = [[] for _ in places]
    for offset, transition in enumerate(transitions):
        for place_index, weight in enumerate(transition["input_vector"]):
            if weight not in (0, 1):
                raise ValueError("weighted arcs are not supported")
            if weight:
                inputs_by_place[place_index].append(offset)
        for place_index, weight in enumerate(transition["output_vector"]):
            if weight not in (0, 1):
                raise ValueError("weighted arcs are not supported")
            if weight:
                outputs_by_place[place_index].append(offset)

    source = f'''// Code generated by scripts/generate_gnark_model.py; DO NOT EDIT.
package circuit

var sepsisInitialMarking = [PlaceCount]int{{{", ".join(map(str, model["initial_marking"]))}}}
var sepsisFinalMarking = [PlaceCount]int{{{", ".join(map(str, model["final_marking"]))}}}
var sepsisTransitionLabels = [TransitionCount]int{{{", ".join(map(str, labels))}}}
var sepsisTransitionModelCosts = [TransitionCount]int{{{", ".join(map(str, model_costs))}}}

// Values are zero-based transition offsets. The witness uses one-based IDs.
var sepsisInputTransitionsByPlace = {go_nested(inputs_by_place)}
var sepsisOutputTransitionsByPlace = {go_nested(outputs_by_place)}
'''
    args.output.write_text(source)


if __name__ == "__main__":
    main()
